apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  lables:
    app: products
spec:
  replicas: 3
  selector:
    matchLables:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: registry.gitlab.com/sali21/ms-products
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001

